### ISSUE TITLE
Draft User Research Plan

### ISSUE THREAD

**Issue by hannahkane** [mozillascience/site#81]
Before we make a decision on the site architecture (see nav_ideas tab of [this doc](https://docs.google.com/spreadsheets/d/1iiUwf_GTXMdV3vB7Tl0h-bCpm1QBumPExkkTL_ktgMQ/edit#gid=719229321)) let's see which ideas resonate with community members. 

@acabunoc @zee-moz @auremoser - can you connect me with ~7 community members who are familiar with the MSL offerings? 

@my-le and @kristinashu and I can connect separately about how to best collect their input and share back with everyone.

**Comment by auremoser** [comment]
@acabunoc @zee-moz do you think this would be something we could appropriately ask on the Gitter chat for OLC? I would say let' s make a voting forum and launch on the Community Call but that's (now) a month away. Perhaps it's appropriate for the Project Call Abby? We could also bring it up in the OLC calls this week @acabunoc but I think that might distract from the purpose of those calls.

I think it would be helpful to actually talk to people rather than just take a poll/form responses, so that's why I suggested the calls as a forum for this. Otherwise, here are a few folks I think we could reach out to independently, who might give us feedback:

* Madeleine Bonsma
* Bastian Greshake
* Fatma Guerfali + Amel Ghouila
* Fellows (Richard, Jason, Joey, Christie)
* Tim Head
* ?? others?

**Comment by stephwright** [comment]
Tom Hohenstein?

Also, wondering if we want 1 or 2 peeps outside MSL but inside MoFo for feedback?  Just thinking in terms of community, they too are our community... right? 
Only thinking about this because in the past our Library redesigned our website seeking only feedback from external users and when the finished product came out, they'd removed all the features that helped the librarians use the site.

**Comment by zee-moz** [comment]
Can we also tap more people who are outside of the Americas/Europe? I know
we have Amel and Fatma, but how about Nifras and Acon?
I think Tom and Madeleine would have great feedback, but we could also ask
Rob Schaefer (U MN) and some of the UBC SG people, as a way to get them
re-engaged (and avoid burning out our superstars).

z

On Wed, Feb 17, 2016 at 10:18 AM, Stephanie Wright <notifications@github.com

**Comment by auremoser** [comment]
O.k. sure, good points, so:
* Bastian Greshake (Europe)
* Fatma Guerfali + Amel Ghouila (Africa)
* Bill Mills / Joey (UBC - Canada)?
* Fellows (Richard, Jason, Christie)
* Hana Sun (inside mofo, new-ish!)
* Amira Dhalla (inside mofo)
* Ancon Paul (Asia)

I made the previous list based on folks who usually respond to email pretty quickly. We're missing representation

**Comment by stephwright** [comment]
:+1:

**Comment by hannahkane** [comment]
This is great, thanks! @my-le and @kristinashu are going to put together some proposals and then I'll reach out to you to collect contact info for these community members so we can share and gather feedback.

**Comment by auremoser** [comment]
Perfect.

**Comment by hannahkane** [comment]
@kristinashu and I spoke earlier. Started drafting a testing plan [here](https://docs.google.com/document/d/1oe8AwqMiKh97558mC5Q9Scs3RWrnFPsCrDxrlX5HCw4/edit#).

Would welcome feedback from all, and will talk specifically with @my-le about this tomorrow!

**Comment by kristinashu** [comment]
We're hoping to email everyone tomorrow so please let us know if you have any feedback.

@auremoser thanks for putting this the list of participants together. Could you please email me their addresses?

**Comment by auremoser** [comment]
Surely :)

**Comment by hannahkane** [comment]
I'm going to close this ticket, though people should feel free to continue to comment on the doc if needed. Will open a new ticket for running phase 1.
