### ISSUE TITLE
Wireframes for About page

### ISSUE THREAD

**Issue by hannahkane** [mozillascience/site#83]
Since we don't yet know the site architecture, let's start the UI and UX process with a page like "About," which we're likely to have on the site regardless of the IA.

See #82 for complementary ticket about content

**Comment by hannahkane** [comment]
cc @my-le @kristinashu

**Comment by hannahkane** [comment]
Taking this out of current milestone, in order to focus on homepage instead.

**Comment by kristinashu** [comment]
Side note, @my-le and I have actually been discussing the possibility of not having an About page. The current about page content includes: mission statement, staff and feature contributors. The mission statement could be incorporated on the home page. Staff and featured contributors profiles could be in a different section (not sure where yet) and we could use tags to filter/highlight them. So the home page could maybe have a line of text "meet our staff" and link to the filtered directory page. Default view for the directory would show the featured profiles.

**Comment by stephwright** [comment]
I know our focus is the home page now but throwing this out there so I don't forget about it.  I'm curious, since one of our big issues is that folks don't understand what it is we do, would it be better to keep the About page but add more content to explain it better?  I would be really interested to hear what the folks we identified as community members would like to know "about" Mozilla Science Lab.

**Comment by hannahkane** [comment]
+1 to getting input from community members. Also, we can think outside of the box—"About" could mean "About Open Science," for example. (Though I agree that an About page might not be necessary at all.)

**Comment by hannahkane** [comment]
Closing given IA decisions so far. Can re-open if About page becomes a necessity.
