### ISSUE TITLE
Finalize content for the Home Page

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/site#86]
We'd love to see the home page better represent the Science Lab.

Looping in @zee-moz & @auremoser here help figure out what should go on our new home page!

See related #87, with UI/UX work on the home page

**Comment by auremoser** [comment]
Apologies in advance for the length of this post, I got excited. :boom: 

The [MLab's site](http://www.measurementlab.net/) has a similar structure to ours, but I kind of like the video embedded as a way to introduce the science lab and what we do, maybe we could film this ourselves and include cameos from our calls to illustrate how the Science Lab is built from a distributed team, and "mobile labs" globally, without too much focus on the lab members (as in the About page).

![screen shot 2016-02-18 at 3 56 15 pm](https://cloud.githubusercontent.com/assets/1559703/13157845/1a14d018-d658-11e5-9e52-396bfbaf287a.png)

I also like the 2-part nav, where the header has two calls to action ("Help us grow and improve" button leads to -> http://www.measurementlab.net/contribute), maybe we could put in the [Training](https://mozillascience.org/training) page  "be a mentor" and "be a learner" content at the end of these links. And then the secondary nav has other options.

![screen shot 2016-02-18 at 3 56 23 pm](https://cloud.githubusercontent.com/assets/1559703/13157809/e892c6c6-d657-11e5-8316-fa28a3a866e9.png)

I like Contribute | Collaborate | Convene options for the header more now, like the [CCC option in the nav suggestions](https://docs.google.com/spreadsheets/d/1iiUwf_GTXMdV3vB7Tl0h-bCpm1QBumPExkkTL_ktgMQ/edit#gid=719229321) where:
* **Contribute** leads to "contribution" or ["training"](https://mozillascience.org/training) options (study group, curriculum, calls to join)
* **Collaborate** leads to ["collaborate" platform page](https://mozillascience.org/collaborate)
* **Convene** leads to events, currently on the ["community" page](https://mozillascience.org/community)

#### Sites I like:
1. http://www.measurementlab.net/ - dissected above, not advocating for the carousel at the top however, I find those distracting.
![screen shot 2016-02-18 at 4 33 24 pm](https://cloud.githubusercontent.com/assets/1559703/13158892/0c3eed0c-d65d-11e5-9324-3cd4ed77b8ed.png)

2. https://cartodb.com/ - mostly for the "call to action" built in to highlight blog posts at the top of the page, the "main nav" is always the most recent blog post, because the blog is hidden in sub-navs. I think that gives the site a fresh and active feel for people who only make it to the home page
![screen shot 2016-02-18 at 3 57 29 pm](https://cloud.githubusercontent.com/assets/1559703/13157833/0a98750e-d658-11e5-82c2-1485747e5177.png)
3. https://opennews.org/ - there's a neatness to the ON site too, simple nav with human-readable headers. "who we are" "what we do" "[how to] get involved".
![screen shot 2016-02-18 at 3 59 09 pm](https://cloud.githubusercontent.com/assets/1559703/13157921/65ec15b4-d658-11e5-9e61-eb39a5eb850f.png)
4. http://robdunnlab.com/ - nice alliterative nav - "People" "Projects" "Publications" "Press", I also like how instead of a mission statement there are keywords under the website title.
![screen shot 2016-02-18 at 4 23 59 pm](https://cloud.githubusercontent.com/assets/1559703/13158754/61cde9d6-d65c-11e5-863e-3502e0f3d287.png)
5. https://www.zooniverse.org/ - love how this has a nav and only one thing above the fold, a call to action button. On scroll down, you get a few animated illustrations demo'ing site contents, I like that too.
![screen shot 2016-02-18 at 4 25 37 pm](https://cloud.githubusercontent.com/assets/1559703/13158746/5500820e-d65c-11e5-8ce9-ab3832309b49.png)
6. http://www.milkywayproject.org/ - a zooniverse project, simple site with some stats above the fold, and I like that, the first thing people see is a really simple set of numbers about us, our contributors, our project count, our events/calls count, and a simple "start classifying button" as a single call to action, not a few buttons splintering visitor interest.
![screen shot 2016-02-18 at 4 26 12 pm](https://cloud.githubusercontent.com/assets/1559703/13158749/5a7847da-d65c-11e5-92da-b26dff9b1b4f.png)
7. http://sciencehackny.com/ - not to push to heavy on the retrofuturism but I also like the simplicity of this site (for an event, but still).
![screen shot 2016-02-18 at 4 31 43 pm](https://cloud.githubusercontent.com/assets/1559703/13158865/f2e90a36-d65c-11e5-930d-669f249ee99f.png)

**Comment by acabunoc** [comment]
For content, here's our latest mission statement we wrote in the fall where we tried to accurately reflect our program and offerings (emphasis mine)

---

The Mozilla Science Lab works to make research collaborative, accessible, and usable. We do this by:

- Empowering the next generation of leaders through **fellowships** and **mentorship**;
- Facilitating project-based learning around **open data** and **open source**;
- And supporting and advocating for a **growing community of researchers working openly**.

**Comment by acabunoc** [comment]
Also, @auremoser -- I think a lot of your comments are more related to some of the other issues: #84 for IA, #87 for home page UI/UX, along with this one! Thanks for some great inspiration :smile:

**Comment by auremoser** [comment]
Oh, do you want me to move them @acabunoc ? I'm sorry! I should have written some more content instead.

**Comment by zee-moz** [comment]
I like the idea of an intro video--- we really need a good way to communicate what we do and why.
Looking at the mission (thanks @acabunoc) , maybe a verb that could come into the IA would be "lead" --- that gives us a way to highlight fellows and the cohort, as well as SG leads? I think the teach/learn separation doesn't work well, as the SGs are very casual and a mix of teaching and learning for all... Slicing and dicing content here gets tricky, since SGs are communities where people learn, and Collaborate is a space for project-based learning but is also a community. etc... hm.

**Comment by hannahkane** [comment]
Great benchmarks and thoughts so far. I've copied some of the comments that are specifically related to IA over to #84, though I realize it's often hard to think about a homepage and not also think about navigation.

So, it sounds like for homepage content, so far we have the idea of a video and something that conveys the scope of the mission. Does that seem right to everyone?

**Comment by acabunoc** [comment]
@hannahkane that sounds about right to me!

However, I'm a bit worried about how we're going to produce a high quality video -- do we have time/resources to do this? I've never made a good quality video so this is very daunting to me.

**Comment by zee-moz** [comment]
Kaitlin and I have been talking about generating some A/V for the web and
for our materials. I'm looking into options and costs so will know more
soon.

Z

**Comment by acabunoc** [comment]
Sent out meeting invite to @mozillascience/msl-staff to plan home page content on Monday

**Comment by hannahkane** [comment]
Great. Let us know how it goes, or if you'd like for a designer to attend. I'd also be happy to attend.

**Comment by acabunoc** [comment]
Thanks @hannahkane! I added you, @my-le & @kristinashu as optional in the invite :)

**Comment by acabunoc** [comment]
Notes from today's meeting: https://public.etherpad-mozilla.org/p/sciencelab-homepage-content

**Comment by hannahkane** [comment]
Next steps: @kaythaney, @hannahkane and @kristinashu to come up with specific copy/content suggestions by Friday. Others are welcome to as well! :)

**Comment by hannahkane** [comment]
Started a [brainstorming document](https://docs.google.com/document/d/1k2Ds-iw4B_Sh5ae1areW1qfuLPtSqmgohtXYBkOi7r4/edit#), experimenting with different "flavors" of writing styles. @kaythaney @zee-moz @stephwright @auremoser @acabunoc @kristinashu - feel free to comment

**Comment by hannahkane** [comment]
Thanks for all the feedback so far. Going to roll this into the next heartbeat to give us more time to brainstorm. @kaythaney - will you be the ultimate decider on final copy?

**Comment by kaythaney** [comment]
yep - put me down for that one. :)

On Thu, Feb 25, 2016 at 3:12 PM, hannahkane <notifications@github.com>
wrote:

> Thanks for all the feedback so far. Going to roll this into the next
> heartbeat to give us more time to brainstorm. @kaythaney
> <https://github.com/kaythaney> - will you be the ultimate decider on
> final copy?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozillascience/site/issues/86#issuecomment-188959696>.
>



-- 
@kaythaney <http://twitter.com/kaythaney/>
@MozillaScience <http://twitter.com/mozillascience>

**Comment by hannahkane** [comment]
I re-organized the [doc](https://docs.google.com/document/d/1k2Ds-iw4B_Sh5ae1areW1qfuLPtSqmgohtXYBkOi7r4/edit#heading=h.90tw9v54omys) a bit and added a Table of Contents so we can easily see the different pieces of content we need to finalize. Also added a few questions for the group.

Would be great if people could go in one more time to add more ideas and opinions. Don't be afraid to say what you don't like; nixing things is really helpful at this point (I'm using strikethrough to cross off lines that ppl don't like so far).

The plan we discussed at the kickoff meeting today:
 * MSL staff will articulate more opinions so we can narrow down our options
 * HK to check in with Comms team to see when they'd like to be involved
 * Once we've narrowed down the options to several that we think are workable, let's take this to the Fellows!
 * Can consider broader user input at that point (perhaps depending on timeline)

**Comment by cassiemc** [comment]
As discussed at today's stand I will review this from a design perspective, @hannahkane and I can clean up and remove some of the noise, @kaythaney will work on some of the longer/more descriptive copy and then put a final stamp of approval.

**Comment by cassiemc** [comment]
We've done some cleanup in the doc but I think the finalization or near-finalization of home page content should wait for the IA results, which we should hear back on soon. Then we can use the content doc to help reinforce those themes and decisions.

**Comment by kaythaney** [comment]
thanks, cassie. i also added some "open science" primer language, that i'd
love your thoughts on.

On Thu, Mar 3, 2016 at 5:53 PM, Cassie McDaniel <notifications@github.com>
wrote:

> We've done some cleanup in the doc but I think the finalization or
> near-finalization of home page content should wait for the IA results,
> which we should hear back on soon. Then we can use the content doc to help
> reinforce those themes and decisions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozillascience/site/issues/86#issuecomment-192005297>.
>



-- 
@kaythaney <http://twitter.com/kaythaney/>
@MozillaScience <http://twitter.com/mozillascience>

**Comment by hannahkane** [comment]
Thanks to @cassiemc and @kaythaney for the updates. If you check out the [doc](https://docs.google.com/document/d/1k2Ds-iw4B_Sh5ae1areW1qfuLPtSqmgohtXYBkOi7r4/edit#heading=h.sr1d8andeat3) now, you'll see a final suggestion for the homepage content. It includes: a tagline, a short section for "About MSL," a short blurb on "What is Open Science?," and very brief descriptions of our programmatic offerings.

Would love final copy edits from @kaythaney. 

My only concern here is that it's a lot of content for the homepage. @kristinashu—can you take a look and advise on whether it needs to be cut down further?

**Comment by kristinashu** [comment]
The amount of copy looks good to me.

**Comment by kaythaney** [comment]
Thumbs up on this end. Thanks, all!

On Mon, Mar 7, 2016 at 4:20 PM, Kristina <notifications@github.com> wrote:

> The amount of copy looks good to me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozillascience/site/issues/86#issuecomment-193456529>.
>



-- 
@kaythaney <http://twitter.com/kaythaney/>
@MozillaScience <http://twitter.com/mozillascience>

**Comment by hannahkane** [comment]
Sweet. I'm going to close this ticket! Thanks, everyone!
